WebPhoneBook 2.0/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using WebPhoneBook_2._0.Models;
using WebPhoneBook_2._0.Entitys;
using WebPhoneBook_2._0.ContextFolder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.AspNetCore.Mvc.Core.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebPhoneBook_2._0.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebPhoneBook_2._0.Controllers
{
    public class BookController : Controller
    {
        //List<Person> Persons;
        private readonly IPersonData Persons;
        public BookController(IPersonData persons)
        {
            Persons = persons;
        }

        //вызов базовой страницы
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<Person> people = Persons.GetPeople().ToList();
            ViewBag.PersonsContext = people;
            return View();
        }

        //вызов страницы контакта 
        [AllowAnonymous]
        public IActionResult Person(string id)
        {
            int h_id = Convert.ToInt32(id);
            IEnumerable<Person> People = Persons.GetPeople();
            PersonModel personModel = new PersonModel
            {
                Person = People.First(Person => Person.Id == h_id),
            };
            return View("Person", personModel);
        }
        #region Добавление контака
        [HttpGet, Authorize]
        public IActionResult AddPerson() //вызов страницы добавления контакта
        {
            return View();
        }

        /// <summary>
        /// Метод добавления нового контакта
        /// </summary>
        /// <param name="Name"></param>
        /// <param name="LastName"></param>
        /// <param name="MiddleName"></param>
        /// <param name="PhoneNumber"></param>
        /// <param name="Address"></param>
        /// <param name="Description"></param>
        /// <returns></returns>
        public IActionResult AddNewPerson(string Name, string LastName, string MiddleName, 
            string PhoneNumber, string Address, string Description)
        {
            Person NewPerson = new Person(Name, LastName, MiddleName,
                PhoneNumber, Address, Description);
            Persons.AddPerson(NewPerson);

            return Redirect("~/"); //возврат к первой странице
        }
        #endregion

        #region Изменение контакта


        
        [HttpGet, Authorize(Roles = "Admin")]
        public IActionResult EditPerson(int id) //вызов страницы изменения контакта
        {
            IEnumerable<Person> People = Persons.GetPeople();
            Person personNow
                = People.First(Person => Person.Id == id);
            ViewBag.PersonNow = personNow;
            return View();
        }

        /// <summary>
        /// Метод изменения данных контакта
        /// </summary>
        /// <param name="id"></param>
        /// <param name="NewName"></param>
        /// <param name="NewLastName"></param>
        /// <param name="NewMiddleName"></param>
        /// <param name="NewPhoneNumber"></param>
        /// <param name="NewAddress"></param>
        /// <param name="NewDescription"></param>
        /// <returns></returns>
        public IActionResult EditPersonContext(int id, string NewName, string NewLastName, string NewMiddleName,
            string NewPhoneNumber, string NewAddress, string NewDescription) 
        {
            Person newdataperson = new Person(NewName, NewLastName, NewMiddleName, NewPhoneNumber, NewAddress, NewDescription);
            Persons.EditPerson(id, newdataperson);
            return Redirect("~/"); //возврат к главной странице
        }
        #endregion 


        /// <summary>
        /// Удаление контакта
        /// </summary>
        /// <param name="id">Идентификатор контакта</param>
        /// <returns></returns>
        [HttpGet, Authorize(Roles = "Admin")]
        public IActionResult DeletePerson(int id)
        {
            Persons.RemovePerson(id);
            return Redirect("~/"); //обновление главной страницы
        }
     
    }
}

WebPhoneBook 2.0/ViewComponents/HeaderButtViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPhoneBook_2._0.ViewComponents
{
    public class HeaderButtViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebPhoneBook 2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - Записная книжка</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">Записная книжка </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div> @await Component.InvokeAsync("HeaderButtView") </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Записная книжка - <a asp-area="" asp-controller="Book" asp-action="index">Index</a>
        </div>
    </footer>
</body>
</html>